### ISSUE TITLE
Is a "Real Robot version" still relevant ? 

### ISSUE THREAD

**Issue by StanSmooth** [davidbsp/patrolling_sim#4]
Hi davidbsp, 
first of all, thank you for your work ! On the README, you mentioned a possible merged coming soon, implementing "a distributed execution of the patrolling environment that can be used also on real robots."
Is this merged still relevant ? What do we have to do to use one of your algorithm on real robots ? 
Best regards.

**Comment by davidbsp** [comment]
Hi @StanSmooth, sorry for the (very) late answer.

As of 2022, we're not planning to share a specific version of patrolling_sim for real robots, due to the fact that the parameters would be a bit specific to the robots we would be using, and there is no standard multimaster approach for multi-robot systems.

If you're still interested, I would advise you to have a look at [this paper](https://drive.google.com/open?id=1Ai4fRZnJ4oNBJFFl7J2Im3YRTakdE45L), especially section 3.6, where you can find guidelines for doing this with real robots.

As far as I am aware, multimaster_fkie is still the best multimaster approach for ROS1 out there.
